package com.marksmile.icp.tools.db.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBeianDomainInfo<M extends BaseBeianDomainInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setDomainName(java.lang.String domainName) {
		set("domain_name", domainName);
	}
	
	public java.lang.String getDomainName() {
		return getStr("domain_name");
	}

	public void setBeianNo(java.lang.String beianNo) {
		set("beian_no", beianNo);
	}
	
	public java.lang.String getBeianNo() {
		return getStr("beian_no");
	}

	public void setBeianCompany(java.lang.String beianCompany) {
		set("beian_company", beianCompany);
	}
	
	public java.lang.String getBeianCompany() {
		return getStr("beian_company");
	}

	public void setBeianCompanyType(java.lang.String beianCompanyType) {
		set("beian_company_type", beianCompanyType);
	}
	
	public java.lang.String getBeianCompanyType() {
		return getStr("beian_company_type");
	}

	public void setBeianSiteName(java.lang.String beianSiteName) {
		set("beian_site_name", beianSiteName);
	}
	
	public java.lang.String getBeianSiteName() {
		return getStr("beian_site_name");
	}

	public void setBeianSiteUrl(java.lang.String beianSiteUrl) {
		set("beian_site_url", beianSiteUrl);
	}
	
	public java.lang.String getBeianSiteUrl() {
		return getStr("beian_site_url");
	}

	public void setBeianTime(java.lang.String beianTime) {
		set("beian_time", beianTime);
	}
	
	public java.lang.String getBeianTime() {
		return getStr("beian_time");
	}

	public void setSpriderDate(java.util.Date spriderDate) {
		set("sprider_date", spriderDate);
	}
	
	public java.util.Date getSpriderDate() {
		return get("sprider_date");
	}

	public void setSourceType(java.lang.String sourceType) {
		set("source_type", sourceType);
	}
	
	public java.lang.String getSourceType() {
		return getStr("source_type");
	}

	public void setBeianType(java.lang.String beianType) {
		set("beian_type", beianType);
	}
	
	public java.lang.String getBeianType() {
		return getStr("beian_type");
	}

	public void setStateType(java.lang.String stateType) {
		set("state_type", stateType);
	}
	
	public java.lang.String getStateType() {
		return getStr("state_type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
