package com.marksmile.icp.tools.db.model;

import com.marksmile.icp.tools.db.model.base.BaseBeianDomainInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BeianDomainInfo extends BaseBeianDomainInfo<BeianDomainInfo> {
	public static final BeianDomainInfo dao = new BeianDomainInfo().dao();
}
